version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: wine-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: wine-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  vault:
    image: hashicorp/vault:latest
    container_name: wine-vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN}
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -dev -dev-listen-address=0.0.0.0:8200 -dev-root-token-id=myroot

  vault-init:
    image: hashicorp/vault:latest
    depends_on:
      - vault
    volumes:
      - ./scripts:/scripts
    environment:
      - DB_APP_USER=${DB_APP_USER}
      - DB_APP_PASSWORD=${DB_APP_PASSWORD}
      - VAULT_TOKEN=${VAULT_TOKEN}
    entrypoint: /bin/sh /scripts/init_vault.sh

  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: wine-oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=${DB_ROOT_PASSWORD}
      - APP_USER=${DB_APP_USER}
      - APP_USER_PASSWORD=${DB_APP_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5

  wine-api:
    build: .
    container_name: wine-quality-api
    ports:
      - "5000:5000"
    environment:
      - MODEL_PATH=/app/models/wine_model.pkl
      - SCALER_PATH=/app/models/scaler.pkl
      - KAFKA_BROKER=kafka:29092
      - KAFKA_TOPIC=wine_predictions
      - KAFKA_PARTITIONS=3
    depends_on:
      - kafka

  # НОВЫЙ СЕРВИС
  wine-consumer:
    build: .
    container_name: wine-consumer
    command: python src/kafka_consumer.py
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN}
      - DB_DSN=oracle-db:1521/FREEPDB1
      - KAFKA_BROKER=kafka:29092
      - KAFKA_TOPIC=wine_predictions
    depends_on:
      oracle-db:
        condition: service_healthy
      vault-init:
        condition: service_completed_successfully
      kafka:
        condition: service_started