name: CD Pipeline

on:
  workflow_dispatch:  # По требованию (ручной запуск)
  schedule:           # По расписанию
    - cron: '0 0 * * 0'
  workflow_run:       # Вызов с последнего этапа CI
    workflows: ["CI Pipeline"]
    branches: [main]
    types:
      - completed

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/wine-quality-model

jobs:
  # Деплой и функциональное тестирование
  deploy-and-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Start full environment via Docker Compose
        run: |
          sed -i "s|build: .|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest|g" docker-compose.yml
          docker-compose up -d

      - name: Wait for API and Infrastructure
        run: |
          echo "waiting for services to initialize..."
          sleep 40 # время Oracle и Kafka подняться
          
          for i in {1..15}; do
            if curl -s -f http://localhost:5000/health; then
              echo "Service is healthy"
              exit 0
            fi
            echo "Retry $i/15..."
            sleep 5
          done
          echo "Health check failed. Logs:"
          docker-compose logs
          exit 1

      - name: Run scenario tests
        run: |
          pip install requests
          python scripts/run_scenario_tests.py scenario.json

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test_results/
          retention-days: 7

      - name: Stop and cleanup environment
        if: always()
        run: |
          docker-compose down -v || true

      - name: Update dev_sec_ops.yml with commit hashes
        if: success()
        run: |
          echo "📝 Updating dev_sec_ops.yml with latest commits..."
          git log -5 --format='- hash: "%H"%n  message: "%s"%n  author: "%an"%n  date: "%ad"' --date=format:"%Y-%m-%d" > commits_tmp.txt
          cat commits_tmp.txt